"""Klopfenstein taper .kicad_mod footprint generator.

Generates a two-port RF footprint with electrically sane copper:

  Variant A (primary): Custom SMD pad containing full taper geometry
    - Pad "1" = custom pad at input end with taper body as primitive
    - Pad "1" = routing pad at output end (same name → same net)
    - One net, one continuous copper primitive, DRC-correct

  Variant B (debug): Port-labeled pads with separate pad numbers
    - Pad "1" at input, Pad "2" at output, fp_poly taper body
    - For visual debugging / port identification only

Coordinate convention (footprint-local, extends along +x):
  Input landing center at x = 0
  Input landing spans  x = [-L_land_start/2, +L_land_start/2]
  Taper body           x = [L_land_start/2, L_land_start/2 + L_body]
  Output landing center x = L_land_start/2 + L_body + L_land_end/2

Pad dimensions (KiCad convention):
  x-size = landing length (along footprint)
  y-size = microstrip width

No RF core code is modified by this module.
"""

from __future__ import annotations

import os
import pathlib
import platform
from dataclasses import dataclass
from typing import List, Optional, Tuple

import numpy as np

from rfcore.klopfenstein import KlopfensteinProfile


# ---------------------------------------------------------------------------
# Defaults
# ---------------------------------------------------------------------------

_DEFAULT_LANDING_M = 0.5e-3     # 0.5 mm default landing length
_PAD_OVERLAP_M = 5e-6           # 5 µm overlap into pads for connectivity
_MIN_LANDING_M = 50e-6          # 50 µm minimum landing


@dataclass
class FootprintSpec:
    """Parameters for footprint generation."""
    profile: KlopfensteinProfile
    fp_name: str = "KlopfensteinTaper"
    layer: str = "F.Cu"
    landing_start_m: float = _DEFAULT_LANDING_M
    landing_end_m: float = _DEFAULT_LANDING_M
    overlap_m: float = _PAD_OVERLAP_M

    # Metadata
    ZS: float = 50.0
    ZL: float = 75.0
    Gamma_m: float = 0.05
    f_start_hz: float = 1e9
    f_stop_hz: float = 10e9
    stackup_name: str = "RO4350B_10mil"


# ---------------------------------------------------------------------------
# Internal: taper polygon points in footprint-local mm
# ---------------------------------------------------------------------------

def _taper_polygon_mm(spec: FootprintSpec) -> List[Tuple[float, float]]:
    """Build closed taper polygon in footprint-local mm coordinates.

    Covers input landing + taper body + output landing as one
    continuous polygon.  Includes overlap into pad anchor regions.
    """
    profile = spec.profile
    w_start = float(profile.w_layout[0])
    w_end = float(profile.w_layout[-1])
    L_body = float(profile.L)
    L_s = max(spec.landing_start_m, _MIN_LANDING_M)
    L_e = max(spec.landing_end_m, _MIN_LANDING_M)

    body_start = L_s / 2   # metres from origin

    z_samples = profile.z_samples
    w_layout = profile.w_layout

    left_pts: list = []
    right_pts: list = []

    # ── Input landing section (constant width = w_start) ──
    x0_mm = (-L_s / 2) * 1e3
    hw_start_mm = (w_start / 2) * 1e3
    left_pts.append((x0_mm, -hw_start_mm))
    right_pts.append((x0_mm, hw_start_mm))

    x1_mm = (body_start) * 1e3
    left_pts.append((x1_mm, -hw_start_mm))
    right_pts.append((x1_mm, hw_start_mm))

    # ── Taper body (Klopfenstein profile) ──
    for i in range(len(z_samples)):
        z = float(z_samples[i])
        w = float(w_layout[i])
        x_mm = (body_start + z) * 1e3
        hw_mm = (w / 2) * 1e3
        left_pts.append((x_mm, -hw_mm))
        right_pts.append((x_mm, hw_mm))

    # ── Output landing section (constant width = w_end) ──
    body_end = body_start + L_body
    x_end_mm = (body_end + L_e) * 1e3
    hw_end_mm = (w_end / 2) * 1e3
    left_pts.append((x_end_mm, -hw_end_mm))
    right_pts.append((x_end_mm, hw_end_mm))

    # Closed polygon: left forward + right reverse
    return left_pts + list(reversed(right_pts))


def _pts_to_str(pts: List[Tuple[float, float]]) -> str:
    """Format polygon points as KiCad s-expression."""
    return "\n        ".join(
        f"(xy {x:.6f} {y:.6f})" for x, y in pts
    )


def _descr(spec: FootprintSpec) -> str:
    """Metadata description string."""
    L_body = float(spec.profile.L)
    L_s = max(spec.landing_start_m, _MIN_LANDING_M)
    L_e = max(spec.landing_end_m, _MIN_LANDING_M)
    L_total = L_s + L_body + L_e
    return (
        f"Klopfenstein taper: "
        f"ZS={spec.ZS:.0f}ohm to ZL={spec.ZL:.0f}ohm, "
        f"Gm={spec.Gamma_m:.3f}, "
        f"f={spec.f_start_hz/1e9:.1f}-{spec.f_stop_hz/1e9:.1f}GHz, "
        f"L_body={L_body*1e3:.2f}mm, "
        f"L_total={L_total*1e3:.2f}mm, "
        f"stackup={spec.stackup_name}, "
        f"generated by uKad"
    )


# ---------------------------------------------------------------------------
# Variant A: Primary — Custom pad with taper as primitive (one net)
# ---------------------------------------------------------------------------

def generate_footprint(spec: FootprintSpec) -> str:
    """Generate primary .kicad_mod: custom pad containing full taper geometry.

    This is the electrically robust variant:
    - Pad "1" at input = custom SMD pad with taper polygon as copper primitive
    - Pad "1" at output = simple SMD pad (same pad name → same net)
    - The taper body is part of pad "1"'s copper → guaranteed connectivity
    - DRC treats entire footprint as one connected copper primitive
    - All copper appears in Gerber export

    Returns .kicad_mod file content.
    """
    profile = spec.profile
    layer = spec.layer

    w_start = float(profile.w_layout[0])
    w_end = float(profile.w_layout[-1])
    L_body = float(profile.L)
    L_s = max(spec.landing_start_m, _MIN_LANDING_M)
    L_e = max(spec.landing_end_m, _MIN_LANDING_M)

    # Pad 1 (input anchor): at x=0
    pad1_sx = L_s * 1e3
    pad1_sy = w_start * 1e3

    # Pad 1 (output routing): same pad name "1" → same net
    body_start = L_s / 2
    body_end = body_start + L_body
    pad_out_cx = (body_end + L_e / 2) * 1e3
    pad_out_sx = L_e * 1e3
    pad_out_sy = w_end * 1e3

    # Text positions
    max_w = max(pad1_sy, pad_out_sy)
    text_cx = pad_out_cx / 2

    # Taper polygon as custom pad primitive (relative to pad center at 0,0)
    poly = _taper_polygon_mm(spec)
    # Remove input landing part from primitive (covered by anchor pad)
    # Actually, include the full polygon — the custom pad primitive adds
    # copper ON TOP of the anchor, so overlap is fine.
    pts_str = _pts_to_str(poly)

    desc = _descr(spec)

    return f'''(footprint "{spec.fp_name}"
  (version 20240101)
  (generator "uKad-klopfenstein")
  (generator_version "1.0")
  (layer "{layer}")
  (descr "{desc}")
  (attr smd)
  (fp_text reference "REF**" (at {text_cx:.4f} {-(max_w/2 + 1.5):.4f}) (layer "{layer}")
    (effects (font (size 1 1) (thickness 0.15)))
  )
  (fp_text value "{spec.fp_name}" (at {text_cx:.4f} {(max_w/2 + 1.5):.4f}) (layer "{layer}")
    (effects (font (size 1 1) (thickness 0.15)))
  )
  (fp_text user "${{REFERENCE}}" (at {text_cx:.4f} {-(max_w/2 + 3.0):.4f}) (layer "F.Fab")
    (effects (font (size 1 1) (thickness 0.15)))
  )
  (pad "1" smd custom
    (at 0 0)
    (size {pad1_sx:.6f} {pad1_sy:.6f})
    (layers "{layer}" "F.Paste" "F.Mask")
    (options (clearance outline) (anchor rect))
    (primitives
      (gr_poly
        (pts
          {pts_str}
        )
        (width 0)
        (fill yes)
      )
    )
  )
  (pad "1" smd rect
    (at {pad_out_cx:.6f} 0)
    (size {pad_out_sx:.6f} {pad_out_sy:.6f})
    (layers "{layer}" "F.Paste" "F.Mask")
  )
)
'''


# ---------------------------------------------------------------------------
# Variant B: Debug — Port-labeled pads (separate pad numbers)
# ---------------------------------------------------------------------------

def generate_footprint_debug(spec: FootprintSpec) -> str:
    """Generate debug .kicad_mod: separate Pad 1/Pad 2 with fp_poly body.

    This variant uses separate pad numbers for port identification.
    The fp_poly taper body is graphical copper on the copper layer.

    WARNING: If Pad 1 and Pad 2 are assigned to different nets in the
    schematic/netlist, the taper body will not be DRC-connected.
    Use this only for debugging / visual inspection.
    """
    profile = spec.profile
    layer = spec.layer

    w_start = float(profile.w_layout[0])
    w_end = float(profile.w_layout[-1])
    L_body = float(profile.L)
    L_s = max(spec.landing_start_m, _MIN_LANDING_M)
    L_e = max(spec.landing_end_m, _MIN_LANDING_M)

    pad1_sx = L_s * 1e3
    pad1_sy = w_start * 1e3

    body_start = L_s / 2
    body_end = body_start + L_body
    pad2_cx = (body_end + L_e / 2) * 1e3
    pad2_sx = L_e * 1e3
    pad2_sy = w_end * 1e3

    max_w = max(pad1_sy, pad2_sy)
    text_cx = pad2_cx / 2

    poly = _taper_polygon_mm(spec)
    pts_str = _pts_to_str(poly)
    desc = _descr(spec) + " [DEBUG/PORT-LABELED]"

    return f'''(footprint "{spec.fp_name}_debug"
  (version 20240101)
  (generator "uKad-klopfenstein")
  (generator_version "1.0")
  (layer "{layer}")
  (descr "{desc}")
  (attr smd)
  (fp_text reference "REF**" (at {text_cx:.4f} {-(max_w/2 + 1.5):.4f}) (layer "{layer}")
    (effects (font (size 1 1) (thickness 0.15)))
  )
  (fp_text value "{spec.fp_name}_debug" (at {text_cx:.4f} {(max_w/2 + 1.5):.4f}) (layer "{layer}")
    (effects (font (size 1 1) (thickness 0.15)))
  )
  (pad "1" smd rect
    (at 0 0)
    (size {pad1_sx:.6f} {pad1_sy:.6f})
    (layers "{layer}" "F.Paste" "F.Mask")
  )
  (pad "2" smd rect
    (at {pad2_cx:.6f} 0)
    (size {pad2_sx:.6f} {pad2_sy:.6f})
    (layers "{layer}" "F.Paste" "F.Mask")
  )
  (fp_poly
    (pts
      {pts_str}
    )
    (stroke (width 0) (type solid))
    (fill solid)
    (layer "{layer}")
  )
)
'''


# ---------------------------------------------------------------------------
# Dimensions / metadata
# ---------------------------------------------------------------------------

def footprint_dimensions(spec: FootprintSpec) -> dict:
    """Return key dimensions of the footprint for UI display."""
    profile = spec.profile
    L_body = float(profile.L)
    w_start = float(profile.w_layout[0])
    w_end = float(profile.w_layout[-1])
    L_s = max(spec.landing_start_m, _MIN_LANDING_M)
    L_e = max(spec.landing_end_m, _MIN_LANDING_M)
    L_total = L_s + L_body + L_e

    return {
        "L_body_mm": L_body * 1e3,
        "L_landing_start_mm": L_s * 1e3,
        "L_landing_end_mm": L_e * 1e3,
        "L_total_mm": L_total * 1e3,
        "w_start_mm": w_start * 1e3,
        "w_end_mm": w_end * 1e3,
        "pad1_x_mm": 0.0,
        "pad2_x_mm": (L_s / 2 + L_body + L_e / 2) * 1e3,
    }


# ---------------------------------------------------------------------------
# Library management
# ---------------------------------------------------------------------------

def default_library_path() -> pathlib.Path:
    """Detect the best default footprint library path.

    Strategy:
    1. KICAD_USER_FOOTPRINT_DIR environment variable
    2. KiCad 8 standard user path (platform-specific)
    3. Fallback to ~/KiCad_Libraries/
    """
    env_dir = os.environ.get("KICAD_USER_FOOTPRINT_DIR")
    if env_dir:
        return pathlib.Path(env_dir) / "Klopfenstein_Tapers.pretty"

    system = platform.system()
    home = pathlib.Path.home()

    if system == "Darwin":
        kicad_dir = home / "Documents" / "KiCad" / "8.0" / "3rdparty"
    elif system == "Windows":
        kicad_dir = home / "Documents" / "KiCad" / "8.0" / "3rdparty"
    else:
        kicad_dir = home / ".local" / "share" / "kicad" / "8.0" / "3rdparty"

    if kicad_dir.exists():
        return kicad_dir / "Klopfenstein_Tapers.pretty"

    return home / "KiCad_Libraries" / "Klopfenstein_Tapers.pretty"


def save_footprint(
    content: str,
    fp_name: str,
    library_path: Optional[pathlib.Path] = None,
) -> pathlib.Path:
    """Save .kicad_mod footprint into a .pretty library directory."""
    if library_path is None:
        library_path = default_library_path()

    library_path = pathlib.Path(library_path)
    if not library_path.name.endswith(".pretty"):
        library_path = library_path / "Klopfenstein_Tapers.pretty"

    library_path.mkdir(parents=True, exist_ok=True)
    fp_path = library_path / f"{fp_name}.kicad_mod"
    fp_path.write_text(content)
    return fp_path


def auto_footprint_name(
    ZS: float, ZL: float, Gamma_m: float, f_start_hz: float,
) -> str:
    """Generate a descriptive footprint name."""
    f_ghz = f_start_hz / 1e9
    gm_str = f"{Gamma_m:.3f}".replace(".", "p")
    return f"Klopfenstein_{ZS:.0f}_to_{ZL:.0f}_Gm{gm_str}_{f_ghz:.0f}GHz"


def library_registration_instructions(library_path: pathlib.Path) -> str:
    """Return user instructions for adding the library to KiCad."""
    return (
        f"Footprint library saved to:\n"
        f"  {library_path}\n\n"
        f"To use in KiCad:\n"
        f"  1. Open KiCad → Preferences → Manage Footprint Libraries\n"
        f"  2. Click 'Add existing library to table' (folder icon)\n"
        f"  3. Navigate to: {library_path}\n"
        f"  4. Click OK\n\n"
        f"The library will appear as 'Klopfenstein_Tapers' in the\n"
        f"footprint browser and placement dialog."
    )
